FROM tensorflow/tensorflow:2.4.1-gpu

RUN apt-get update && apt-get install -y tmux ffmpeg libsm6 libxext6 libxrender-dev wget unrar unzip

# Install Atari environment
RUN pip3 install gym[atari]==0.18.3
RUN pip3 install atari-py
RUN pip3 install tensorflow_probability==0.11.0
